apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: geoinfra
  labels:
    app: prometheus
    component: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "geo-backend"
        metrics_path: /metrics
        scheme: http

        static_configs:
          - targets:
              - "geo-backend:8000"
            labels:
              application: "geoinfra"
              component: "fastapi-backend"
              environment: "development"
