apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-backend
  namespace: geoinfra
  labels:
    app: geo-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: geo-backend

  template:
    metadata:
      labels:
        app: geo-backend

    spec:
      containers:
        - name: backend
          image: geoinfra-backend:9.1
          imagePullPolicy: Never

          command:
            - /bin/sh
            - -c

          args:
            - |
              export DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
              exec uvicorn main:app --host 0.0.0.0 --port 8000

          ports:
            - name: http
              containerPort: 8000

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgis-secret
                  key: POSTGRES_PASSWORD

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
