apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis-data
  namespace: geoinfra
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
