apiVersion: v1
kind: Service
metadata:
  name: geodb
  namespace: geoinfra
  labels:
    app: geodb
spec:
  type: ClusterIP
  selector:
    app: geodb
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
